baseurl = "https://hankli0130.github.io/"
title = "Hank Li"
theme = "minimal"
# disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
defaultContentLanguage = "en"
