[[main]]
url = "/zh/"
name = "首頁"
weight = 1

[[main]]
url = "/zh/about/"
name = "關於我"
weight = 2

[[main]]
url = "/zh/post/"
name = "文章"
weight = 3

[[main]]
url = "/zh/project/"
name = "作品"
weight = 4

[[icon]]
    url = "mailto:hankli0130@gmail.com"
    name = "envelope-o"
    weight = 1

[[icon]]
    url = "https://github.com/HankLi0130/"
    name = "github"
    weight = 2

[[icon]]
    url = "https://twitter.com/HankLi0130/"
    name = "twitter"
    weight = 3

[[icon]]
    url = "https://www.linkedin.com/in/hankli0130/"
    name = "linkedin"
    weight = 4

[[icon]]
    url = "https://www.youtube.com/channel/UCVYje6c5eOPJwu2-1tfQiEw"
    name = "youtube"
    weight = 5