author = "Hank Li"
description = "Life, Tech and stuff"
githubUsername = "HankLi0130"
accent = "gray"
showBorder = true
backgroundColor = "white"
font = "Raleway" # should match the name on Google Fonts!
highlight = true
highlightStyle = "default"
highlightLanguages = ["kotlin", "java"]