author = "Hank Li"
description = "Life, tech and stuff"
githubUsername = "HankLi0130"
accent = "#E4CD05"
showBorder = true
backgroundColor = "white"
font = "RalReway" # should match the name on Google Fonts!
highlight = true
highlightStyle = "default"
highlightLanguages = ["kotlin", "java"]

profilePic = "/profile/hank_head_shot.jpg"
copyright = "Copyright © 2020 Hank Li. All rights reserved."
